[programs.localnet]
escrow = "HG6eAHrTi1WM4QtC9taAiVexvFfDyWbZPCYXNXy5zn4A"

[programs.devnet]
escrow = "HG6eAHrTi1WM4QtC9taAiVexvFfDyWbZPCYXNXy5zn4A"

[programs.testnet]
escrow = "HG6eAHrTi1WM4QtC9taAiVexvFfDyWbZPCYXNXy5zn4A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# cluster = "testnet"
# cluster = "devnet"
# wallet = "./target/giver.json"
# wallet = "./target/taker.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
