[programs.devnet]
escrow = "5wzgkaVnhuWsrxavTdNgCDtoyY6UM6VaYfY14SinS6Fh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./target/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "A7Jh2nb1hZHwqEofm4N8SXbKTj82rx7KUfjParQXUyMQ"
program = "../../target/deploy/store.so"

[[test.genesis]]
address = "2F5NEkMnCRkmahEAcQfTQcZv1xtGgrWFfjENtTwHLuKg"
program = "../../target/deploy/access_controller.so"
